ApplicationName: workerOnBording
Serilog:
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Information
      System: Error
      Microsoft.AspNetCore: Warning     
  WriteTo:
  - Name: Console
    Args: 
        theme: "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Literate, Serilog.Sinks.Console"
        outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} | {ThreadId} | {Level:u4} | {AppDomain} | {SourceContext} | {Message:lj}{NewLine}{Exception}"
  #- Name: File
  #  Args:
  #    path: Logs/log.txt
  #    outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} | {ThreadId} | {Level:u4} | {AppDomain} | {SourceContext} | {Message:lj}{NewLine}{Exception}"
  #    rollingInterval: Day
  #    fileSizeLimitBytes: 10485760
  #    rollOnFileSizeLimit: true
  #    retainedFileCountLimit: 10
  Enrich:
  - FromLogContext
  - WithThreadId

Observability:
  ServerUrls: "https://apm-mon-test.andreani.com"
  ServiceName: "set-proyect-name"